spring:
  application:
    name: personal-finance
  mvc:
    locale-resolver: fixed
    locale: pt_BR
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  secret: ${JWT_SECRET}

springdoc:
  override-with-generic-response: false

---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false
